### ISSUE TITLE
Undefined variable in KSDAGG + wild bootstrap

### ISSUE THREAD

**Issue by XingLLiu** [antoninschrab/ksdagg-paper#1]
Hi,

It seems the variable `bandwidth_multipliers` on the following LOC is undefined.

https://github.com/antoninschrab/ksdagg-paper/blob/99a0179f4a16e824aad3e15c448b42ac924d6b83/ksdagg.py#L50

I presume this line can be fixed by replacing it with `N = 1 + l_plus - l_minus`?

Thanks in advance.

**Comment by antoninschrab** [comment]
Thanks for reporting this issue! This commit should fix it: 980f14a2ecf1dc0cbf45cbe9ce64dab3a6e8f3ec

Let me know if you have other issues running the code!
